name: Build binaries and release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION_STRING: ${{ github.ref_name }}
      REPO_URL: github.com/CrispDeserving/github-actions-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.25"
      - run: go version
      - name: Get Package Dependencies
        run: |
          go get -u .
          go mod tidy
      - name: Build For Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go build -o "dihdah-${GOOS}_${GOARCH}" \
          -ldflags="-s -X ${REPO_URL}/cmd.versionString=${VERSION_STRING}" \
          .
          chmod +x "dihdah-${GOOS}_${GOARCH}"
      - name: Build For MacOS
        env:
          GOOS: darwin
          GOARCH: amd64
        run: |
          go build -o "dihdah-${GOOS}_${GOARCH}" \
          -ldflags="-s -X ${REPO_URL}/cmd.versionString=${VERSION_STRING}" \
          .
          chmod +x "dihdah-${GOOS}_${GOARCH}"
      - name: Build For Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          go build -o "dihdah-${GOOS}_${GOARCH}.exe" \
          -ldflags="-s -X ${REPO_URL}/cmd.versionString=${VERSION_STRING}" \
          .
          chmod +x "dihdah-${GOOS}_${GOARCH}"
      - name: Release to Github
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          make_latest: true
          name: Release ${{ github.ref_name }}
          files: |
            dihdah-*
