name: Go
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION_STRING: ${{ github.event.releases.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.25"
      - run: go version
      - name: Get Package Dependencies
        run: |
          go get -u .
          go mod tidy
      - name: Build For Linux
        run: |
          GOARCH="amd64" GOOS="linux" \
            go build -v -o "dihdah-${GOOS}_${GOARCH}" \
            -ldflags="-X github.com/CrispDeserving/github-actions-test/cmd.versionString=${VERSION_STRING}" \
            .
      - name: Build For Macos
        run: |
          GOARCH="amd64" GOOS="darwin" \
            go build -v -o "dihdah-${GOOS}_${GOARCH}" \
            -ldflags="-X github.com/CrispDeserving/github-actions-test/cmd.versionString=${VERSION_STRING}" \
            .
      - name: Build For Windows
        run: |
          GOARCH="amd64" GOOS="windows" \
            go build -v -o "dihdah-${GOOS}_${GOARCH}.exe" \
            -ldflags="-X github.com/CrispDeserving/github-actions-test/cmd.versionString=${VERSION_STRING}" \
            .
      - name: Release to Github
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          make_latest: true
          name: Release ${{ github.event.release.tag_name }}
          files: |
            dihdah-*
