name: Go
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.25"
      - run: go version

      - name: Get Package Dependencies
        run:|
          go get -u .
          go mod tidy

      - name: Build For Linux
        strategy:
          matrix:
            arch: ["amd64"]
            os: ["linux", "darwin", "macos"]
        env:
          VERSION_STRING: ${{ github.event.releases.tag_name }}
        run: |
          GOARCH="${{ matrix.arch }}" GOOS="${{ matrix.os }}" \
            go build -v -o "dihdah-${GOOS}_${GOARCH}" \
            -ldflags="-X github.com/CrispDeserving/github-actions-test/cmd.versionString=${VERSION_STRING}" \
            .

      - name: Rename Windows Binaries
        run: |
          for f in *windows*; do \
            mv "$f" '$(echo "$f" | sed s/$/.exe/)'; \
          done

      - name: Release to Github
        uses: softprops/action-gh-release@v2
        permissions:
          contents: write
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          make_latest: true
          name: Release ${{ github.event.release.tag_name }}
          files: |
            dihdah-*
